#!/bin/sh /etc/rc.common

START=97
STOP=10
USE_PROCD=1

PROG=/usr/libexec/dynipv6forward

start_service() {
	[ -x "$PROG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG" daemon
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

reload_service() {
	[ -x "$PROG" ] || return 1
	"$PROG" sync
}

service_triggers() {
	procd_add_reload_trigger dynipv6forward network
}
